# Generated by Django 5.0.7 on 2024-08-01 20:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_History',
            fields=[
                ('user_id', models.BigIntegerField()),
                ('chat_id', models.BigIntegerField()),
                ('messages', models.CharField(max_length=500000)),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message_index', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
