# Generated by Django 5.0.7 on 2024-08-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_history',
            name='message_id',
        ),
    ]
